### ISSUE TITLE
Submission note has extension URL hardcoded to the Chrome store despite also being published on mozilla

### ISSUE THREAD

**Issue by sp74fg2** [Serhii-DV/bandcamp-to-discogs#108]
I'm using the extension in Librefox. The draft submission note includes the extension URL hardcoded to the one in the Chrome store which is odd to read. The Mozilla URL would be expected, but maybe linking to the project page is better for general usability?
Personally I would prefer to have no URL at all as including the link in every submission might be considered sudo advertisement down the road? 

https://github.com/Serhii-DV/bandcamp-to-discogs/blob/91486d5041d642f2454d91b4c172351e869ea537/src/config.js#L17

**Comment by Serhii-DV** [comment]
Thank you for the feedback. 
Basically, you can always edit "Notes" on Discogs Edit Release page before submitting the release and remove generated text.

I agree that since there is a Firefox addon it doesn't make sense to have only Google Chrome extension link. 
I'm thinking to change the text to something simple like:

```
This draft was created via CSV upload and "Bandcamp To Discogs" Google Chrome/Firefox extension 
```

without putting the link.
